#! /bin/bash

FILE=$1
d1=$(date +%s%N)
last=0
sum=$(test_telnet | sed '0,/.*Time/d' | sed 's/ [0-9][0-9]:[0-9][0-9]//' | md5sum)
i=0
d2=(date +%s%N)
while [ $i -le 250 ]
do
	sum=$(test_telnet | sed '0,/.*Time/d' | sed 's/ [0-9][0-9]:[0-9][0-9]//' | md5sum)
	if [[ $last == $sum ]]
	then
		i=$(( $i + 1 ))
	else
		i=0
		last=$sum
		d2=$(date +%s%N)
	fi
	sleep 0.1
done
echo $d1 > $FILE
echo $d2 >> $FILE
